# Generated by Django 3.1.8 on 2021-09-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=30, verbose_name='ID в телеграмме')),
                ('username', models.CharField(max_length=30, verbose_name='Юзернейм в телеграмме')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('msk', models.CharField(max_length=5, verbose_name='Разница с Москвой')),
                ('wakeup_time', models.CharField(max_length=10, verbose_name='Время подъема')),
                ('marathon_day', models.PositiveIntegerField(default=0, verbose_name='День марафона')),
                ('failed_days', models.PositiveIntegerField(default=0, verbose_name='Дней пропущено')),
                ('on_marathon', models.BooleanField(default=True, verbose_name='Участвует в марафоне')),
            ],
            options={
                'verbose_name': 'Участник марафона',
                'verbose_name_plural': 'Участники марафона',
            },
        ),
    ]
