# Generated by Django 3.1.8 on 2021-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0004_moderators'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialMarathonMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=30, verbose_name='ID в телеграмме')),
                ('username', models.CharField(default='Отсутствует', max_length=30, verbose_name='Юзернейм в телеграмме')),
                ('last_message', models.CharField(max_length=255, verbose_name='Последнее сообщение')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Пользователь, который запустил бота',
                'verbose_name_plural': 'Пользователи, которые запустили бота',
            },
        ),
        migrations.AddField(
            model_name='moderators',
            name='username',
            field=models.CharField(default='Отсутствует', max_length=30, verbose_name='Юзернейм в телеграмме'),
        ),
        migrations.AlterField(
            model_name='moderators',
            name='telegram_id',
            field=models.CharField(max_length=30, verbose_name='ID в телеграмме'),
        ),
    ]
