# Generated by Django 3.1.8 on 2021-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0005_auto_20210925_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialmarathonmembers',
            name='date',
        ),
        migrations.AlterField(
            model_name='marathonmembers',
            name='msk_timedelta',
            field=models.CharField(max_length=5, verbose_name='Разница с Москвой'),
        ),
        migrations.DeleteModel(
            name='Timestamps',
        ),
    ]
