# Generated by Django 3.1.8 on 2021-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0008_auto_20210926_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathonmembers',
            name='name',
        ),
        migrations.AddField(
            model_name='funnelusers',
            name='started_marathon',
            field=models.BooleanField(default=False, verbose_name='Начал марафон'),
        ),
        migrations.AddField(
            model_name='marathonmembers',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='marathonmembers',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='marathonmembers',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
