# Generated by Django 3.1.8 on 2021-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0009_auto_20210929_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelusers',
            name='last_update_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время последнего сообщения'),
        ),
    ]
