# Generated by Django 3.1.8 on 2021-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0013_auto_20210930_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='file',
        ),
        migrations.AddField(
            model_name='reviews',
            name='photo_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID фотографии'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID видео'),
        ),
    ]
