# Generated by Django 3.1.8 on 2021-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0014_auto_20210930_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonmembers',
            name='marathon_day',
            field=models.PositiveIntegerField(default=1, verbose_name='День марафона'),
        ),
        migrations.AlterField(
            model_name='marathonmembers',
            name='msk_timedelta',
            field=models.IntegerField(default=0, verbose_name='Разница с Москвой'),
        ),
    ]
