# Generated by Django 3.1.8 on 2021-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0015_auto_20211001_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='timestamps',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='first_timestamp_success',
            field=models.BooleanField(default=False, verbose_name='Сдан первый отчет'),
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='last_timestamp_success',
            field=models.BooleanField(default=False, verbose_name='Сдан второй отчет'),
        ),
    ]
