# Generated by Django 3.1.8 on 2021-10-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0016_auto_20211002_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamps',
            old_name='complete',
            new_name='completed',
        ),
    ]
