# Generated by Django 3.1.8 on 2021-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0017_auto_20211002_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamps',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
