# Generated by Django 3.1.8 on 2021-10-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0018_auto_20211002_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamps',
            name='date',
        ),
    ]
