# Generated by Django 3.1.8 on 2021-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0020_timestamps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='report_later',
            field=models.BooleanField(default=False, verbose_name='Отправил отчет с опозданием'),
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='first_timestamp_success',
            field=models.BooleanField(default=False, verbose_name='Вовремя сдан первый отчет'),
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='last_timestamp_success',
            field=models.BooleanField(default=False, verbose_name='Вовремя сдан второй отчет'),
        ),
    ]
