# Generated by Django 3.1.8 on 2021-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0021_auto_20211003_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderators',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='report_later',
            field=models.BooleanField(default=False, verbose_name='Отправил отчеты, но с опозданием'),
        ),
    ]
