# Generated by Django 3.1.8 on 2021-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0022_auto_20211004_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
